include_user_id: False
use_id: "sid"

# model training
flag_add_input_embedding: False
flag_use_output_embedding: False

embedding_loss_weight: 0
sid_loss_weight: 1

evaluation_method: "default"

embedding_head_dict:
  use_new_init: False
  embed_target: ground_truth
  embed_proj_type: mlp

