defaults:
  - base

# model training
flag_add_input_embedding: True
flag_use_output_embedding: True

embedding_loss_weight: 1
sid_loss_weight: 1

evaluation_method: "dense"

embedding_head_dict:
  normalize_logits: True  # flag_use_output_embedding: True
  logits_temperature: 0.07  # flag_use_output_embedding: True

  text_embedding_dim: 768  # flag_add_input_embedding: True
  hidden_sizes: [256, 512, 768]  # flag_add_input_embedding: True
  embd_proj_dropout_rate: 0.5  # flag_add_input_embedding: True
  embd_proj_in_dropout_rate: 0.2  # flag_add_input_embedding: True

